# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "minimal/xenial64"
  config.vm.hostname = "ubuntu-test"

  config.vm.provider :virtualbox do |vb|
    vb.name = "ubuntu-test"
    vb.memory = 512
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  # config.vm.network :private_network, ip: "192.168.0.42"
  # config.vm.provision :shell, path: "bootstrap.sh"
  # config.vm.synced_folder "../data", "/vagrant_data"
end
